### ISSUE TITLE
Gekkigheidje 

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/babylab-admin#37]
Issue op https://babylab-admin2.hum.uu.nl/

Ik heb vandaag een gebouwsluiting toegevoegd van maandag 12-08-2019 08:00 tot vrijdag 16-08-2019 22:00. Die wordt visueel weergegeven in de agenda van maandag tot en met donderdag - de vrijdag ontbreekt dus in de visuele weergave.

Waarschijnlijk komt dit omdat ik in eerste instantie een fout had gemaakt - Ik had de sluiting op de vrijdag maar tot 0:00 uur laten duren. Maar die sluiting heb ik verwijderd en daarna bovenstaande sluiting toegevoegd. En de visuele weergave blijft maar tot donderdagavond duren. (Ook op andere PCs etc).

**Comment by tymees** [comment]
Dit is zeker gek... Zeker aangezien de aangeleverde data voor de calender wel goed is:
```
[
   {
      "title":"Hele gebouw gesloten",
      "allDay":true,
      "start":"2019-08-12T08:00:00+0200",
      "end":"2019-08-16T22:00:00+0200",
      "tooltip":"UITdagen, veel lawaai. zie https:\/\/utrechtseintroductietijd.nl\/",
      "color":"#ff0000"
   }
]
```

Ik ga er naar kijken. Mogelijk is het een probleem met 'allDay'?

**Comment by tymees** [comment]
Hij staat nu wel goed in de calender, door hem naar 2019-08-17 00:00:00 te zetten.

**Comment by irisopgithub** [comment]
ah, dus hij blokt gewoon alleen de hele dag in de visuele weergave als de hele dag ook echt tot middernacht geblokt is?
dat is wel heel logisch natuurlijk.
maar er zit dus iets niet-ergonomisch aan de invoerkant. als mens vind je het niet logisch om een 'tot' te hebben die tot de middernacht aan het begin van de 'tot'-dag gaat. je zou die tot aan de middernacht aan het eind van die dag willen hebben.

**Comment by tymees** [comment]
Ik ben het met je eens dat dit niet de echte oplossing is. Dit is meer een tijdelijke oplossing om verwarring te voorkomen.

Ik ben nu bezig met het uitvogelen waarom hij dit zo doet, dus hopelijk komt er een betere oplossing.

**Comment by tymees** [comment]
Het was uiteindelijk zo dat 'allDay' ervoor zorgt dat hij alleen hele dagen weergeeft.

Dat op `false` zetten heeft het verholpen!

**Comment by irisopgithub** [comment]
cool, tnx!
